spring:
    datasource:
        url: jdbc:h2:mem:mydb
        username: sa
        password: password
        driverClassName: org.h2.Driver
    jpa:
        show-sql: true
        properties: 
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
    h2:
        console: 
            enabled: true
            # default path: h2-console
            path: /h2-ui

    thymeleaf: 
        cache: false
        enabled: true 
        prefix: classpath:/templates/
        suffix: .html